---
# tasks file for imode_prepare
- name: Register to Red Hat CDN and enable the RPM repositories we need
  ansible.builtin.include_role:
    name: "{{ imode_prep_system_roles_collection }}.rhc"
  vars:
    rhc_state: present
    rhc_repositories: "{{ __imode_prep_rhc_repositories + imode_prep_addtl_repositories }}"
- name: Install necessary and additional RPM packages
  ansible.builtin.dnf:
    name: "{{ __imode_prep_rpms + imode_prep_addtl_rpms }}"
    state: present
  become: true
