galaxy_info:
  author: Eric Lavarde
  description: convert a container image for RHEL image mode into a system image
  company: Red Hat

  license: BSD-3-Clause

  min_ansible_version: "2.16"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: EL
      versions: ["9"]

  galaxy_tags: [edge, rhel, microshift]

dependencies: []
